name: totem_touch
description: Tótem interactivo de GPA diseñado para Flutter Web.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  archive: ^4.2.0
  audioplayers: ^6.8.1
  excel_community: ^2.3.0
  flutter:
    sdk: flutter
  http: ^1.6.0
  idb_shim: ^2.9.8
  uuid: ^4.6.0
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/branding/
    - assets/mascot/gp/
    - assets/illustrations/robotics/
    - assets/illustrations/cutting/
    - assets/illustrations/manufacturing/
    - assets/illustrations/machinery/
    - assets/illustrations/software/
    - assets/illustrations/careers/
    - assets/audio/
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope/Manrope-VariableFont_wght.ttf
