import 'interest_node.dart';

abstract final class InterestTree {
  static const roots = <InterestNode>[
    InterestNode(
      id: 'robotica_automatizacion',
      title: 'Robótica & Automatización',
      description: 'Cobots, automatización e inspección.',
      icon: InterestIcon.robotics,
      illustration: InterestIllustration.robot,
      accent: InterestAccent.robotics,
      mascotOutfit: InterestMascotOutfit.robotics,
      children: [
        InterestNode(
          id: 'automatizacion_linea_produccion',
          title: 'Automatización de Línea de Producción',
          icon: InterestIcon.robotics,
          illustration: InterestIllustration.production,
          accent: InterestAccent.robotics,
        ),
        InterestNode(
          id: 'automatizacion_robots',
          title: 'Automatización con Robots',
          icon: InterestIcon.robotics,
          illustration: InterestIllustration.robot,
          accent: InterestAccent.robotics,
        ),
        InterestNode(
          id: 'automatizacion_cobots',
          title: 'Automatización con Cobots',
          icon: InterestIcon.robotics,
          illustration: InterestIllustration.robot,
          accent: InterestAccent.robotics,
        ),
        InterestNode(
          id: 'inspeccion_inteligente',
          title: 'Sistemas de Inspección Inteligente',
          icon: InterestIcon.robotics,
          illustration: InterestIllustration.computer,
          accent: InterestAccent.robotics,
        ),
        InterestNode(
          id: 'celdas_corte_plasma',
          title: 'Celdas de Corte por Plasma',
          icon: InterestIcon.robotics,
          illustration: InterestIllustration.energy,
          accent: InterestAccent.robotics,
        ),
        InterestNode(
          id: 'celdas_corte_laser',
          title: 'Celdas de Corte por Láser',
          icon: InterestIcon.robotics,
          illustration: InterestIllustration.energy,
          accent: InterestAccent.robotics,
        ),
        InterestNode(
          id: 'celdas_corte_waterjet',
          title: 'Celdas de Corte por Waterjet',
          icon: InterestIcon.robotics,
          illustration: InterestIllustration.energy,
          accent: InterestAccent.robotics,
        ),
        InterestNode(
          id: 'industria_salud_biomedica',
          title: 'Industria de la Salud y Biomédica',
          icon: InterestIcon.robotics,
          illustration: InterestIllustration.production,
          accent: InterestAccent.robotics,
        ),
        InterestNode(
          id: 'industria_quimica',
          title: 'Industria Química',
          icon: InterestIcon.robotics,
          illustration: InterestIllustration.production,
          accent: InterestAccent.robotics,
        ),
        InterestNode(
          id: 'industria_aeroespacial',
          title: 'Industria Aeroespacial',
          icon: InterestIcon.robotics,
          illustration: InterestIllustration.production,
          accent: InterestAccent.robotics,
        ),
        InterestNode(
          id: 'industria_educacion',
          title: 'Industria de la Educación',
          icon: InterestIcon.robotics,
          illustration: InterestIllustration.education,
          accent: InterestAccent.robotics,
        ),
      ],
    ),
    InterestNode(
      id: 'sistemas_corte',
      title: 'Sistemas de Corte',
      description: 'Plasma, láser y waterjet.',
      icon: InterestIcon.cutting,
      illustration: InterestIllustration.energy,
      accent: InterestAccent.cutting,
      mascotOutfit: InterestMascotOutfit.cutting,
      children: [
        InterestNode(
          id: 'corte_manual_plasma',
          title: 'Sistema de Corte Manual de Plasma',
          icon: InterestIcon.cutting,
          illustration: InterestIllustration.energy,
          accent: InterestAccent.cutting,
        ),
        InterestNode(
          id: 'corte_plasma',
          title: 'Sistema de Corte con Plasma',
          icon: InterestIcon.cutting,
          illustration: InterestIllustration.energy,
          accent: InterestAccent.cutting,
        ),
        InterestNode(
          id: 'corte_waterjet',
          title: 'Sistema de Corte con Waterjet',
          icon: InterestIcon.cutting,
          illustration: InterestIllustration.energy,
          accent: InterestAccent.cutting,
        ),
        InterestNode(
          id: 'corte_laser',
          title: 'Sistema de Corte con Láser',
          icon: InterestIcon.cutting,
          illustration: InterestIllustration.energy,
          accent: InterestAccent.cutting,
        ),
      ],
    ),
    InterestNode(
      id: 'fabricacion_avanzada',
      title: 'Fabricación Avanzada',
      description: 'Procesos y soluciones de fabricación.',
      icon: InterestIcon.manufacturing,
      illustration: InterestIllustration.production,
      accent: InterestAccent.manufacturing,
      mascotOutfit: InterestMascotOutfit.manufacturing,
      children: [
        InterestNode(
          id: 'diseno_industrial',
          title: 'Diseño Industrial',
          icon: InterestIcon.manufacturing,
          illustration: InterestIllustration.production,
          accent: InterestAccent.manufacturing,
        ),
        InterestNode(
          id: 'software_industrial_medida',
          title: 'Desarrollo de Software Industrial a la Medida',
          icon: InterestIcon.manufacturing,
          illustration: InterestIllustration.computer,
          accent: InterestAccent.manufacturing,
        ),
        InterestNode(
          id: 'racks_dollies_trolleys',
          title: 'Racks, Dollies, Trolleys y Carros de Precisión',
          icon: InterestIcon.manufacturing,
          illustration: InterestIllustration.production,
          accent: InterestAccent.manufacturing,
        ),
        InterestNode(
          id: 'piezas_metalmecanicas_serie',
          title: 'Piezas Metalmecánicas en Serie',
          icon: InterestIcon.manufacturing,
          illustration: InterestIllustration.production,
          accent: InterestAccent.manufacturing,
        ),
        InterestNode(
          id: 'housing_sheet_metal',
          title: 'Housing de Precisión con Sheet Metal',
          icon: InterestIcon.manufacturing,
          illustration: InterestIllustration.production,
          accent: InterestAccent.manufacturing,
        ),
        InterestNode(
          id: 'maquinados_especiales',
          title: 'Maquinados Especiales',
          icon: InterestIcon.manufacturing,
          illustration: InterestIllustration.tools,
          accent: InterestAccent.manufacturing,
        ),
        InterestNode(
          id: 'servicios_industriales',
          title: 'Servicios Industriales (Corte, Doblez, Pailería, Pintura)',
          icon: InterestIcon.manufacturing,
          illustration: InterestIllustration.tools,
          accent: InterestAccent.manufacturing,
        ),
        InterestNode(
          id: 'estructuras_metalmecanicas',
          title: 'Estructuras Metalmecánicas',
          icon: InterestIcon.manufacturing,
          illustration: InterestIllustration.production,
          accent: InterestAccent.manufacturing,
        ),
      ],
    ),
    InterestNode(
      id: 'maquinaria_medida',
      title: 'Maquinaria a la Medida',
      description: 'Ingeniería especializada.',
      icon: InterestIcon.machinery,
      illustration: InterestIllustration.tools,
      accent: InterestAccent.machinery,
      mascotOutfit: InterestMascotOutfit.machinery,
      children: [
        InterestNode(
          id: 'maquinaria_metalmecanica',
          title: 'Industria Metalmecánica',
          icon: InterestIcon.machinery,
          illustration: InterestIllustration.tools,
          accent: InterestAccent.machinery,
        ),
        InterestNode(
          id: 'maquinaria_alimentos',
          title: 'Industria de Alimentos',
          icon: InterestIcon.machinery,
          illustration: InterestIllustration.tools,
          accent: InterestAccent.machinery,
        ),
        InterestNode(
          id: 'maquinaria_construccion',
          title: 'Industria de la Construcción',
          icon: InterestIcon.machinery,
          illustration: InterestIllustration.tools,
          accent: InterestAccent.machinery,
        ),
        InterestNode(
          id: 'maquinaria_automotriz',
          title: 'Industria Automotriz y Autopartes',
          icon: InterestIcon.machinery,
          illustration: InterestIllustration.tools,
          accent: InterestAccent.machinery,
        ),
        InterestNode(
          id: 'maquinaria_agricola',
          title: 'Industria Agrícola y Agroindustrial',
          icon: InterestIcon.machinery,
          illustration: InterestIllustration.tools,
          accent: InterestAccent.machinery,
        ),
        InterestNode(
          id: 'maquinaria_energia',
          title: 'Industria de Energía',
          icon: InterestIcon.machinery,
          illustration: InterestIllustration.energy,
          accent: InterestAccent.machinery,
        ),
        InterestNode(
          id: 'maquinaria_transporte',
          title: 'Industria del Transporte',
          icon: InterestIcon.machinery,
          illustration: InterestIllustration.tools,
          accent: InterestAccent.machinery,
        ),
      ],
    ),
    InterestNode(
      id: 'software_industrial',
      title: 'Software Industrial',
      description: 'Soluciones digitales para industria.',
      icon: InterestIcon.software,
      illustration: InterestIllustration.computer,
      accent: InterestAccent.software,
      mascotOutfit: InterestMascotOutfit.software,
      children: [
        InterestNode(
          id: 'tableros_informacion',
          title: 'Tableros de Información',
          icon: InterestIcon.software,
          illustration: InterestIllustration.computer,
          accent: InterestAccent.software,
        ),
        InterestNode(
          id: 'big_data_ia',
          title: 'Big Data, Ciencia de Datos e IA',
          icon: InterestIcon.software,
          illustration: InterestIllustration.computer,
          accent: InterestAccent.software,
        ),
        InterestNode(
          id: 'apps_industriales',
          title: 'Apps Industriales',
          icon: InterestIcon.software,
          illustration: InterestIllustration.computer,
          accent: InterestAccent.software,
        ),
        InterestNode(
          id: 'aplicativos',
          title: 'Aplicativos',
          icon: InterestIcon.software,
          illustration: InterestIllustration.computer,
          accent: InterestAccent.software,
        ),
        InterestNode(
          id: 'sistemas_web',
          title: 'Sistemas Web',
          icon: InterestIcon.software,
          illustration: InterestIllustration.computer,
          accent: InterestAccent.software,
        ),
      ],
    ),
    InterestNode(
      id: 'vacantes_estadias',
      title: 'Vacantes & Estadías',
      description: 'Forma parte de GPA.',
      icon: InterestIcon.careers,
      illustration: InterestIllustration.education,
      accent: InterestAccent.careers,
      mascotOutfit: InterestMascotOutfit.careers,
      children: [
        InterestNode(
          id: 'vacantes_administrativas_financieras',
          title: 'Vacante en Posiciones Administrativas y Financieras',
          icon: InterestIcon.careers,
          illustration: InterestIllustration.education,
          accent: InterestAccent.careers,
        ),
        InterestNode(
          id: 'vacantes_contables',
          title: 'Vacante en Posiciones Contables',
          icon: InterestIcon.careers,
          illustration: InterestIllustration.education,
          accent: InterestAccent.careers,
        ),
        InterestNode(
          id: 'vacantes_ingenieria',
          title: 'Vacantes en Posiciones de Ingeniería',
          icon: InterestIcon.careers,
          illustration: InterestIllustration.education,
          accent: InterestAccent.careers,
        ),
        InterestNode(
          id: 'vacantes_operacion_produccion',
          title: 'Vacantes en Posiciones de Operación de Producción',
          icon: InterestIcon.careers,
          illustration: InterestIllustration.education,
          accent: InterestAccent.careers,
        ),
        InterestNode(
          id: 'vacantes_capital_humano',
          title: 'Vacantes en Posiciones de Capital Humano',
          icon: InterestIcon.careers,
          illustration: InterestIllustration.education,
          accent: InterestAccent.careers,
        ),
        InterestNode(
          id: 'becario_trainee',
          title: 'Posiciones de Becario / Trainee',
          icon: InterestIcon.careers,
          illustration: InterestIllustration.education,
          accent: InterestAccent.careers,
        ),
      ],
    ),
  ];
}
